version: "3"
services:
  go-web:
    container_name: go-web
    build: .
    tty: true
    volumes:
      - ./gqlgen-todos:/go/src/gqlgen-todos
    ports:
      - "8080:8080"
    environment:
      MONGO_DB_HOST: mongo-db
      MONGO_DB_PORT: 27017
    links:
      - "mongodb:mongodb"
  mongodb:
    container_name: mongodb
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      MONGODB_USER: root
      MONGODB_PASSWORD: root